server:
  port: 8088
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eternity?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    initialSize: 20
    minIdle: 10
    maxActive: 50
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    max-wait: 30000 #连接池最大阻塞时间（负数表示没有限制）
    max-active: 100 # 连接池最大连接数
    max-idle: 20 #
    min-idle: 0 # 连接池最小连接
    timeout: 3000 # 连接超时

  jackson:
    time-zone: GMT+8
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML
    servlet:
       content-type: text/html
mybatis:
  mapperLocations: classpath:mybatis/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      stydu:
        debug
